tabela: mtcars.csv

# modelo: (reg_linear | reg_logistica)
modelo: reg_linear

# reutilizar_modelo: (sim | nao | não) Deve ajustar novamente o modelo ou pegar 
# da pasta /saidas.
reutilizar_modelo: nao

# modelo utilizado para fazer predicao
escolhe_modelo: fit1

pares:
  - "y": mpg
    "x": [wt, drat]
